/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.util.Calendar;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class FrSigno extends javax.swing.JFrame {

    /**
     * Creates new form FrSigno
     */
    public FrSigno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        lbDia = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        lbMes = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        lbAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbResumo = new javax.swing.JLabel();
        lbResumo1 = new javax.swing.JLabel();
        lbResumo2 = new javax.swing.JLabel();
        lbResumo3 = new javax.swing.JLabel();
        rbCasado = new javax.swing.JRadioButton();
        rbSolteiro = new javax.swing.JRadioButton();
        rbSeparado = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();
        rbViuvo = new javax.swing.JRadioButton();
        lbEstadoCivil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MESTRE DO ZODÍ4CO.com");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 20, 990, -1));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome ");
        jPanel1.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 750, 35));

        lbSexo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(255, 255, 255));
        lbSexo.setText("Sexo:");
        jPanel1.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        rbMasc.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbMasc);
        rbMasc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbMasc.setForeground(new java.awt.Color(255, 255, 255));
        rbMasc.setSelected(true);
        rbMasc.setText("Masculino");
        rbMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMascActionPerformed(evt);
            }
        });
        jPanel1.add(rbMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        rbFem.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbFem);
        rbFem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbFem.setForeground(new java.awt.Color(255, 255, 255));
        rbFem.setText("Feminino");
        jPanel1.add(rbFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 120, -1));

        lbDia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDia.setForeground(new java.awt.Color(255, 255, 255));
        lbDia.setText("Dia");
        jPanel1.add(lbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txtDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 43, -1));

        lbMes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbMes.setForeground(new java.awt.Color(255, 255, 255));
        lbMes.setText("Mês");
        jPanel1.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        txtMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 45, -1));

        lbAno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAno.setForeground(new java.awt.Color(255, 255, 255));
        lbAno.setText("Ano");
        jPanel1.add(lbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        txtAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 63, -1));

        btConsultar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 311, 150, 50));

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("/");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("/");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        lbResumo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbResumo.setForeground(new java.awt.Color(255, 255, 255));
        lbResumo.setText("Resumo:");
        jPanel1.add(lbResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        lbResumo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResumo1.setForeground(new java.awt.Color(255, 255, 255));
        lbResumo1.setText("Resumo");
        jPanel1.add(lbResumo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        lbResumo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResumo2.setForeground(new java.awt.Color(255, 255, 255));
        lbResumo2.setText("Resumo");
        jPanel1.add(lbResumo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        lbResumo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResumo3.setForeground(new java.awt.Color(255, 255, 255));
        lbResumo3.setText("Resumo");
        jPanel1.add(lbResumo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        rbCasado.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbCasado);
        rbCasado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbCasado.setForeground(new java.awt.Color(255, 255, 255));
        rbCasado.setText("Casado(a)");
        jPanel1.add(rbCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 130, -1));

        rbSolteiro.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbSolteiro);
        rbSolteiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSolteiro.setForeground(new java.awt.Color(255, 255, 255));
        rbSolteiro.setSelected(true);
        rbSolteiro.setText("Solteiro(a)");
        jPanel1.add(rbSolteiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 130, -1));

        rbSeparado.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbSeparado);
        rbSeparado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSeparado.setForeground(new java.awt.Color(255, 255, 255));
        rbSeparado.setText("Separado(a)");
        jPanel1.add(rbSeparado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 140, 30));

        rbDivorciado.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbDivorciado);
        rbDivorciado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbDivorciado.setForeground(new java.awt.Color(255, 255, 255));
        rbDivorciado.setText("Divorciado(a)");
        jPanel1.add(rbDivorciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 140, -1));

        rbViuvo.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbViuvo);
        rbViuvo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbViuvo.setForeground(new java.awt.Color(255, 255, 255));
        rbViuvo.setText("Viúvo(a)");
        jPanel1.add(rbViuvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 130, -1));

        lbEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        lbEstadoCivil.setText("Estado Cívil");
        jPanel1.add(lbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 90, 70));

        txtIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zodiaco1.jpg"))); // NOI18N
        jPanel1.add(txtIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesActionPerformed

    private void rbMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMascActionPerformed
    public int nomear(String nome) {
        int cont = 0;
        cont = (nome.length());
        if (cont >= 8) {
            nome = txtNome.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Se esforça ai! Assim poderemos lhe oferecer melhores informações.");
        }
        return cont;
    }

    public String fazerTratamento() {
        String trato = "";
        if (rbMasc.isSelected()) {
            if (rbSolteiro.isSelected()) {
                trato = " ";
            } else {
                trato = "Sr.";
            }
        } else {
            if (rbSolteiro.isSelected()) {
                trato = "Srta.";
            } else {
                trato = "Sra.";
            }
        }
        return trato;
    }

    public String nascer() {
        String data = "";
        int dia = Integer.parseInt(txtDia.getText()), mes = Integer.parseInt(txtMes.getText()), ano = Integer.parseInt(txtAno.getText());
        Calendar hoje = Calendar.getInstance();
        int diaA, mesA, anoA;
        diaA = hoje.get(Calendar.DATE);
        mesA = hoje.get(Calendar.MONTH)+1;
        anoA = hoje.get(Calendar.YEAR);
        if (dia <= 0 || dia > 31 || mes <= 0 || mes > 12 || ano < 1900 || ano > anoA) {
            JOptionPane.showMessageDialog(null, "Dia, mes ou ano invalido!!");
        } else {
            if (mes == 3 && dia >= 21 && dia <= 31) {
                data = "Você é do signo Áries";
            } else if (mes == 4 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Áries";
                txtIMG.setIcon(new ImageIcon(getClass().getResource("/img/aries.png")));
               // txtIMG.setIcon("//aries.png");
            } else if (mes == 4 && dia >= 21 && dia <= 30) {
                data = "Você é do signo Touro";
            } else if (mes == 4 && dia == 31) {
                data = "O mês informado só tem 30 dias!";
            } else if (mes == 5 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Touro";
            } else if (mes == 5 && dia >= 21 && dia <= 31) {
                data = "Você é do signo Gemêos";
            } else if (mes == 6 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Gemêos";
            } else if (mes == 6 && dia >= 21 && dia <= 30) {
                data = "Você é do signo Câncer";
            } else if (mes == 7 && dia >= 1 && dia <= 21) {
                data = "Você é do signo Câncer";
            } else if (mes == 6 && dia == 31) {
                data = "O mês informado só tem 30 dias!";
            } else if (mes == 7 && dia >= 22 && dia <= 31) {
                data = "Você é do signo Leão";
            } else if (mes == 8 && dia >= 1 && dia <= 22) {
                data = "Você é do signo Leão";
            } else if (mes == 8 && dia >= 23 && dia <= 31) {
                data = "Você é do signo Virgem";
            } else if (mes == 9 && dia >= 1 && dia <= 22) {
                data = "Você é do signo Virgem";
            } else if (mes == 9 && dia >= 23 && dia <= 30) {
                data = "Você é do signo Libra";
            } else if (mes == 10 && dia >= 1 && dia <= 22) {
                data = "Você é do signo Libra";
            } else if (mes == 9 && dia == 31) {
                data = "O mês informado só tem 30 dias!";
            } else if (mes == 10 && dia >= 23 && dia <= 31) {
                data = "Você é do signo Escorpião";
            } else if (mes == 11 && dia >= 1 && dia <= 21) {
                data = "Você é do signo Escorpião";
            } else if (mes == 11 && dia >= 22 && dia <= 30) {
                data = "Você é do signo Sagitário";
            } else if (mes == 12 && dia >= 1 && dia <= 21) {
                data = "Você é do signo Sagitário";
            } else if (mes == 11 && dia == 31) {
                data = "O mês informado só tem 30 dias!";
            } else if (mes == 12 && dia >= 22 && dia <= 31) {
                data = "Você é do signo Capricórnio";
            } else if (mes == 1 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Capricórnio";
            } else if (mes == 1 && dia >= 21 && dia <= 31) {
                data = "Você é do signo AquarianoNato";
            } else if (mes == 2 && dia >= 1 && dia <= 19) {
                data = "Você é do signo AquarianoNato";
            } else if (mes == 2 && dia >= 20 && dia <= 28) {
                data = "Você é do signo Peixes";
            } else if (mes == 3 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Peixes";
            } else if (mes == 2 && dia >= 29) {
                data = "O mês informado só tem 28 dias!";
            }
        }
        return data;
    }

    public int gerarNum() {
        int n;
        n = (int) (Math.random() * 12) + 1;
        return n;
    }

    public String gerarCor() {
        String corAleatoria;
        String[] cor = {"Verde", "Azul", "Roxo", "Vermelho", "Amarelo", "Rosa", "Preto", "Branco", "Laranja", "Marrom", "Cinza", "Violeta"};
        Random randomCor = new Random();
        int vet = cor.length;
        int i = randomCor.nextInt(vet);
        String cores = cor[i];
        return cores;
    }
    public int calcularIdade(){
        int idade;
        int dia = Integer.parseInt(txtDia.getText()), mes = Integer.parseInt(txtMes.getText()), ano = Integer.parseInt(txtAno.getText());
         Calendar hoje = Calendar.getInstance();
        int diaA, mesA, anoA;
        diaA = hoje.get(Calendar.DATE);
        mesA = hoje.get(Calendar.MONTH)+1;
        anoA = hoje.get(Calendar.YEAR);
        idade=((anoA*365+mesA*12+diaA)-(ano*365+mes*12+dia))/365;
        
        return idade;
    }
    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        String nome, data;
        int dia, mes, ano, nome2, num;
        nome = txtNome.getText();
        nome2 = nomear(nome);

        dia = Integer.parseInt(txtDia.getText());
        mes = Integer.parseInt(txtMes.getText());
        ano = Integer.parseInt(txtAno.getText());
        lbResumo1.setText(fazerTratamento() + " " + nome + ", você nasceu dia " + dia + ", do " + mes + ", de " + ano + ".");
        lbResumo2.setText("Você tem "+calcularIdade()+" anos de idade.");
        lbResumo3.setText(nascer()+". Seu número da sorte é: " + gerarNum() + ". Sua cor é: " + gerarCor());
    }//GEN-LAST:event_btConsultarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
       txtNome.setText(null);
       txtDia.setText(null);
       txtMes.setText(null);
       txtAno.setText(null);
       rbMasc.setSelected(true);
       rbSolteiro.setSelected(true);
       lbResumo1.setText(null);
       lbResumo2.setText(null);
       lbResumo3.setText(null);
       JOptionPane.showMessageDialog(null, "Sessão Finalizada!");
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSigno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSigno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(FrSigno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSigno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSigno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbEstadoCivil;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbResumo;
    private javax.swing.JLabel lbResumo1;
    private javax.swing.JLabel lbResumo2;
    private javax.swing.JLabel lbResumo3;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JRadioButton rbSeparado;
    private javax.swing.JRadioButton rbSolteiro;
    private javax.swing.JRadioButton rbViuvo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JLabel txtIMG;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
